id: 00a4dc85da104cf4a19e3891dbcec9e0
initial_creation_type: ocr
source_metadata:
  volumes:
    6c2b1384406a4ec29fc1fda4038a87be:
      base_file: v096.txt
      image_group_id: I1PD95942
      title: ''
      total_pages: 1198
      volume_number: 97
